//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerfulWindSlickedBackHair.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerfulWindSlickedBackHair.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 バックグラウンド 的本地化字符串。
        /// </summary>
        internal static string BackgroundTitle {
            get {
                return ResourceManager.GetString("BackgroundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 犬 的本地化字符串。
        /// </summary>
        internal static string DogTitle {
            get {
                return ResourceManager.GetString("DogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 風がとても強いです!\r\n私の犬全体が吹き飛ばされようとしています! 的本地化字符串。
        /// </summary>
        internal static string NotificationsFromDog {
            get {
                return ResourceManager.GetString("NotificationsFromDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ペーシング。。。 的本地化字符串。
        /// </summary>
        internal static string PacingTitle {
            get {
                return ResourceManager.GetString("PacingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鳩 的本地化字符串。
        /// </summary>
        internal static string PigeonsTitle {
            get {
                return ResourceManager.GetString("PigeonsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 強風オールバック\r\nしかしWindows 的本地化字符串。
        /// </summary>
        internal static string PowerfulWindButWindowsText {
            get {
                return ResourceManager.GetString("PowerfulWindButWindowsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知の緑色のボール 的本地化字符串。
        /// </summary>
        internal static string UnknownGreenSphereTitle {
            get {
                return ResourceManager.GetString("UnknownGreenSphereTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口笛を吹く 的本地化字符串。
        /// </summary>
        internal static string WhistleTitle {
            get {
                return ResourceManager.GetString("WhistleTitle", resourceCulture);
            }
        }
    }
}
